Search and filter enhancement
HughCraig/GHAP pull request #235
Opened 2023-08-26 04:22 UTC by MufengNiu

2023-08-28 04:49 UTC, yangli0516 requested changes

2023-08-28 04:49 UTC, yangli0516 commented on app/Http/Controllers/GazetteerController.php
For search names from the description, please implement the same thing for bulk names search (from file upload).

2023-08-29 22:33 UTC, MufengNiu commented
@yangli0516 Updated

2023-08-30 01:20 UTC, yangli0516 approved these changes

2023-08-30 01:20 UTC, merged